### ISSUE TITLE
LIS3DH_DATARATE_LOWPOWER_5KHZ mode is not setting the accelerometer in 5kHz low power mode but in 1.344 kHz High resolution mode

### ISSUE THREAD

**Issue by nalexopo** [adafruit/Adafruit_LIS3DH#14]
lis.setDataRate(LIS3DH_DATARATE_LOWPOWER_5KHZ);

 Above code is not setting the accelerometer in 5kHz mode but in 1.344 kHz High resolution mode. I read the LIS3DH_REG_CTRL1 register and i get a value b'1001 0111. It should be  b'1001 1111 for 5kHz low power mode and the HR bit in LIS3DH_REG_CTRL4 should be 0. Read Lis3dh datasheet in page 35/54.

**Comment by erichiggins** [comment]
I was looking into setting a faster data rate in my sketch and came across this reported issue.  I haven't tried implementing it yet, but I wanted to share some additional information from the docs in case it helps anyone to confirm (and/or fix) the issue reported above.

Based on what I've read and the information below, I _believe_ the following code is needed to use low-power (5khz) mode.  **Please double-check before trying it for yourself.**

```
// Enable all axes, low-power mode
writeRegister8(LIS3DH_REG_CTRL1, 0xf);
// 5khz data rate
setDataRate(LIS3DH_DATARATE_LOWPOWER_5KHZ);
// High res off,  BDU enabled
writeRegister8(LIS3DH_REG_CTRL4, 0x80);
```

## Datasheet info
The following is taken directly from page 9 of the [Application Note](https://cdn-shop.adafruit.com/datasheets/LIS3DHappnote.pdf).

> Referring to the LIS3DH datasheet, output data rate (ODR) and low power enable (LPen)
> bits of `CTRL_REG1` and HR bits of `CTRL_REG4` are used to select the operating modes
> (power-down mode, normal mode and low power mode) and output data rate (Table 2 and
> Table 3).
> 
> **Table 2. Operating mode selection**
> 
> | Operating mode | `CTRL_REG1`[3] (LPen bit) | `CTRL_REG4`[3] (HR bit) | BW [Hz] | Turn-on time [ms] |
> | --- | --- | --- | --- | --- |
> | Low power mode | 1 | 0 | ODR/2 | 1 |
> | Normal mode | 0 | 1 | ODR/9 | 7/ODR |
> 
> **Table 3. Data rate configuration**
> 
> | ODR3 | ODR2 | ODR1 | ODR0 | Power mode selection |
> | --- | --- | --- | --- | --- |
> | 0 | 0 | 0 | 0 | Power-down mode |
> | 0 | 0 | 0 | 1 | Normal/low power mode (1 Hz) |
> | 0 | 0 | 1 | 0 | Normal/low power mode (10 Hz) |
> | 0 | 0 | 1 | 1 | Normal/low power mode (25 Hz) |
> | 0 | 1 | 0 | 0 | Normal/low power mode (50 Hz) |
> | 0 | 1 | 0 | 1 | Normal/low power mode (100 Hz) |
> | 0 | 1 | 1 | 0 | Normal/low power mode (200 Hz) |
> | 0 | 1 | 1 | 1 | Normal/low power mode (400 Hz) |
> | 1 | 0 | 0 | 0 | Low power mode (1.5 kHz) |
> | 1 | 0 | 0 | 1 | Normal (1.250 kHz)/low power mode (5 kHz) |

I believe these correlate to the [these data rate options in Adafruit_LIS3DH.h](https://github.com/adafruit/Adafruit_LIS3DH/blob/17017f2d7d6b8cb19befb16168c864efb627b130/Adafruit_LIS3DH.h#L98-L111).


## References
- [LIS3DH datasheet](https://cdn-shop.adafruit.com/datasheets/LIS3DH.pdf)
- Setting default rate (400hz), normal mode, and high-res in [Adafruit_LIS3DH.cpp](https://github.com/adafruit/Adafruit_LIS3DH/blob/17017f2d7d6b8cb19befb16168c864efb627b130/Adafruit_LIS3DH.cpp#L106-L112)
- Implementation of [`setDataRate()`](https://github.com/adafruit/Adafruit_LIS3DH/blob/17017f2d7d6b8cb19befb16168c864efb627b130/Adafruit_LIS3DH.cpp#L286-L292)

**Comment by erichiggins** [comment]
@ladyada Is this repo still being maintained? There are several open PRs and Issues, like this one, which have not had responses.

**Comment by nalexopo** [comment]
@erichiggins  

 Some suggestions from my part as I just saw that you replied.


1. Don't use the datasheet from adafruit site but rather the one from ST site because it has been revised a few times from the 2010 version your link leads to. This is the 2016 version you can see some differences in the ODR that's why i am talking about 1.344 kHz and not 1.250 kHz.

Here the December 2016 version which is the current version. 
[https://www.st.com/resource/en/datasheet/lis3dh.pdf](url)

2. If you are planning on going full speed on this sensor have a look on the application note page 9/59
you may be limited by bandwidth limitations when using HR mode.

https://www.st.com/content/ccc/resource/technical/document/application_note/77/ed/e7/e1/28/5a/45/d6/CD00290365.pdf/files/CD00290365.pdf/jcr:content/translations/en.CD00290365.pdf

**Comment by hakeemta** [comment]
> HR bit in LIS3DH_REG_CTRL5

HR bit is in LIS3DH_REG_CTRL4

**Comment by T-Mosher** [comment]
Note, same issue raised via this forum thread:
https://forums.adafruit.com/viewtopic.php?t=211362

Is this issue pending a resolution, stuck, or merely forgotten?

**Comment by tyeth** [comment]
Hardware arriving on Wednesday, so I'll have a look + test then

**Comment by tyeth** [comment]
Hey @nalexopo @erichiggins @hakeemta @T-Mosher, there is a PR in to add the functionality, see #50 , it would be really appreciated if you folks could give it a thorough testing!

There is a new constructor argument (**frequency** - last arg for SPI overloads, defaulting to 500kHz) to allow raising the SPI frequency as needed for the 5KHz rate. I went up to 2MHz. 
There is a new method for **setPerformanceMode** to allow selecting low power / normal / high resolution modes

**Comment by T-Mosher** [comment]
Sorry, can't test it, don't have the hardware.

**Comment by tyeth** [comment]
@nalexopo @erichiggins @hakeemta final testing reminder prod ☝️  before I merge it tomorrow and release anyway. We can always fix it afterwards.

**Comment by erichiggins** [comment]
I'm currently traveling and unable to test this

**Comment by tyeth** [comment]
Thanks for the thought, and happy travels!

**Comment by tyeth** [comment]
Please feel free to reopen or create a new issue if there are any problems with the release (1.3.0).
