### ISSUE TITLE
Wrong read on Arduino Nano

### ISSUE THREAD

**Issue by pardoc** [adafruit/Adafruit_LIS3DH#2]
On Arduino Nano, the read() method gives wrong data.
When X changes, it impact Y and Z readings.
When Y changes, it impacts Z and readings.
This seems to come from the burst read of x,y, and z value (I2C read with autoincrement).
When I patch the library to read these data with separate readRegister8() calls, it works OK.

**Comment by hoffmannjan** [comment]
Tested this few times on UNO and all seems to be OK. As this issue is pretty old - closing It - please reopen if problem persist for you :).
