### ISSUE TITLE
Wrong divider values

### ISSUE THREAD

**Issue by raziel2k** [adafruit/Adafruit_LIS3DH#34]
Maybe I'm wrong but I think that the values for the divider in the code are wrong. For example: according to the datasheet (page 10) with FS bits set to 00 (2G), the mg/digit is 1. This means that the 12 bits value (with high resolution mode) express directly a value in mg (thousandths of G). Since the value in the registers is zero left padded, to convert it in G, it should be divided by 16000 (first divide by 16 to right shift by 4 and then by 1000 to pass from thousandths G to G) and not 16380. For the same reason, the divider for 4G should be 8000, at 8G 4000 and 1333 at 16G.
I did some tests with 3 different accelerometer and using my dividers I obtain values closer to 1 for the module (when the device don't move) than with your value.

**Comment by siddacious** [comment]
Fixed via #35
