### ISSUE TITLE
How to read and print out the value of the register

### ISSUE THREAD

**Issue by krupis** [adafruit/Adafruit_LIS3DH#41]
I have added my own custom function to Adafruit_LIS3DH library:
```
uint8_t Adafruit_LIS3DH::read_register(uint16_t register){
    Adafruit_BusIO_Register reg_to_read = Adafruit_BusIO_Register(
    i2c_dev, spi_dev, ADDRBIT8_HIGH_TOREAD, register, 1);
    return reg_to_read.read();

}
  
```

I simply want to be able to read a value in a register, and from what I am aware, there is no such possibility in the library so I have added my own. So as an argument, I want to be able to pass an address of the register ( for example LIS3DH_REG_CTRL4) this is a keyword defined in header file.

In my arduino main file, I am calling this function:
```
  int reg_to_read;
  reg_to_read = lis.read_register(LIS3DH_REG_CTRL4);
  Serial.println(reg_to_read);
```
But it is not working for some reason, the error message is displayed:
```
C:\Users\petrikas.lu\Documents\Arduino\libraries\Adafruit_LIS3DH-master\Adafruit_LIS3DH.cpp: In member function 'uint8_t Adafruit_LIS3DH::read_register(uint16_t)':
C:\Users\petrikas.lu\Documents\Arduino\libraries\Adafruit_LIS3DH-master\Adafruit_LIS3DH.cpp:468:66: error: expected primary-expression before '(' token
     Adafruit_BusIO_Register reg_to_read = Adafruit_BusIO_Register(
                                                                  ^
C:\Users\petrikas.lu\Documents\Arduino\libraries\Adafruit_LIS3DH-master\Adafruit_LIS3DH.cpp:469:45: error: expected primary-expression before 'register'
     i2c_dev, spi_dev, ADDRBIT8_HIGH_TOREAD, register, 1);
                                             ^

```

It somehow does not like that I want to pass the register as an argument, can someone clarify to me why is that?

If I change my function and hardcode the register into it, it works without any issues:
```
uint8_t Adafruit_LIS3DH::read_register(uint8_t register){
    Adafruit_BusIO_Register reg_to_read = Adafruit_BusIO_Register(
    i2c_dev, spi_dev, ADDRBIT8_HIGH_TOREAD, LIS3DH_REG_CTRL4, 1);
    return reg_to_read.read();

}
```

Notice in the code above, I have hardoced LIS3DH_REG_CTRL4 for the reg_to_read and that seems to work fine! How can I get it to work if I want to pass an address like an argument to the function?

**Comment by ladyada** [comment]
this is a good question for a coding forum, it isnt an issue with the library. thanks!
