### ISSUE TITLE
Accelerometer readings without using FIFO

### ISSUE THREAD

**Issue by krupis** [adafruit/Adafruit_LIS3DH#43]
Hello. I am using accelldemo example provided with the library. If I understand correctly, lis.read() function reads the accelerometer data using FIFO method. Is there an example code that I can use to read the data without the FIFO? 

I am experiencing some fluctuation in accelerometer readings (noisy output), I have read the following thread:
https://community.st.com/s/question/0D50X00009XkXrR/lis3dh-z-output-noisy
and someone suggested turning OFF fifo and just reading the data regularly. I wonder whether that would provide more accurate output

**Comment by ladyada** [comment]
all examples are already included. there is no fifo used.
