### ISSUE TITLE
How to select between multiple HW SPI interfaces

### ISSUE THREAD

**Issue by krupis** [adafruit/Adafruit_LIS3DH#44]
Hello. I am using this library for my ESP32 device. The ESP32 has 2 available SPI interfaces. When I initialise the LIS3DH using HW SPI interface the following method is executed:
```
Adafruit_LIS3DH::Adafruit_LIS3DH(int8_t cspin, SPIClass *theSPI) {
  _cs = cspin;
  _mosi = -1;
  _miso = -1;
  _sck = -1;
  _sensorID = -1;
  SPIinterface = theSPI;
}
```

I think by default. the ESP32 selects GPIO23(MOSI), GPIO19(MISO), SCLK(18) as HW SPI, but what about other HW SPI pins? GPIO12(MISO), GPIO13(MOSI), GPIO14(CLOCK) how can I select those if in my custom PCB I have used those as my SPI pins?

If I create them as part of Software SPI even though they are hardware SPI pins , is there gonna be any drawbacks?

**Comment by caternuson** [comment]
That information is in the variant definition as part of the ESP32 Arduino Board Support Package:
https://github.com/espressif/arduino-esp32/tree/master/variants
You would need to add something like that for your custom PCB.

Alternatively, look here:
https://github.com/espressif/arduino-esp32/blob/master/libraries/SPI/examples/SPI_Multiple_Buses/SPI_Multiple_Buses.ino
You could maybe use that approach in your sketch. And then pass in the SPIClass reference as the second parameter when creating the LIS3DH instance.
